#file: noinspection YAMLSchemaValidation
name: "pnpm-git-flow"
description: ""
inputs:
  shell:
    description: "The shell to use for any steps that use shells"
    default: "bash"
    required: "true"

runs:
  using: "composite"
  steps:
    - name: "Setup Node.js"
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "pnpm"

    - name: "Install ripgrep"
      shell: ${{ inputs.shell }}
      run: |
        sudo apt-get update
        sudo apt-get install -y ripgrep

    - name: "Install dependencies"
      shell: ${{ inputs.shell }}
      run: |
        pnpm install --frozen-lockfile

    - name: "Build"
      shell: ${{ inputs.shell }}
      run: |
        pnpm build

    - name: "Globally Install"
      shell: ${{ inputs.shell }}
      run: |
        pnpm setup
