blank_issues_enabled: false
contact_links:
  - name: Ask for help
    url: https://github.com/kaeawc/git-flow-mcp/discussions/new?category=q-a
    about: If you have a usage or debugging question, please use the Q&A feature of the repo's Discussions section.
